Repository Arquisoft/wichat_es5b, pull requests merged in 2025-02, with the labels that each got.

#19 Punto 2 Documentacion
  docs/src/02_architecture_constraints.adoc
Labels: documentation

#36 Documentación Punto 4
  docs/src/04_solution_strategy.adoc
Labels: documentation

#37 Acabado punto 8 Documentacion
  docs/src/08_concepts.adoc
Labels: documentation

#58 Interfaz grafica del juego pelayo
  webapp/src/App.js
  webapp/src/components/Login.js
  webapp/src/components/game/GameQuestion.css
  webapp/src/components/game/GameQuestion.jsx
Labels: task

#64 Acabada versión inicial botones pistas
  webapp/src/components/Login.js
Labels: LLM
